# Generated by Django 5.1.5 on 2025-02-17 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_details_customertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertList',
            fields=[
                ('property_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_list_title', models.CharField(max_length=100)),
                ('property_detail_remark', models.TextField()),
                ('property_sqrt_start_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_sqrt_end_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_price_start_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_price_end_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_bathroom', models.IntegerField()),
                ('property_kitchne', models.IntegerField()),
                ('property_parking', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyList_created_by', to=settings.AUTH_USER_MODEL)),
                ('property_list_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyList_CityMaster', to='home.citymaster')),
                ('property_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyList_Location', to='home.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PropertyList_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['property_list_id'],
            },
        ),
    ]
