# Generated by Django 5.1.5 on 2025-02-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_details_customertype'),
        ('propertyListing', '0002_propertlist_file_url_propertlist_file_url_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertlist',
            old_name='property_list_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='propertlist',
            old_name='property_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='propertlist',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PropertyList_MasterState', to='home.masterstate'),
            preserve_default=False,
        ),
    ]
