# Generated by Django 5.1.5 on 2025-02-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('propertyListing', '0003_rename_property_list_city_propertlist_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertlist',
            name='bhk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PropertList_BHK', to='masters.bhk'),
            preserve_default=False,
        ),
    ]
