# Generated by Django 5.1.5 on 2025-01-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_referencemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details_CityMaster', to='home.citymaster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details_Location', to='home.location')),
                ('propertyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details_PropertyType', to='home.propertytype')),
                ('referenceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details_ReferenceMaster', to='home.referencemaster')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details_MasterState', to='home.masterstate')),
            ],
            options={
                'ordering': ['details_id'],
            },
        ),
    ]
