# Generated by Django 5.1.5 on 2025-01-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='customerType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Details_CustomerType', to='home.customertype'),
            preserve_default=False,
        ),
    ]
