# Generated by Django 5.1.5 on 2025-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BHK',
            fields=[
                ('bhk_id', models.AutoField(primary_key=True, serialize=False)),
                ('bhk_name', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bhk_id'],
            },
        ),
    ]
